### ISSUE TITLE
Return Gotrue API response content if an exception is thrown

### ISSUE THREAD

**Issue by elrhomariyounes** [supabase/gotrue-csharp#1]
# Feature request

## Is your feature request related to a problem? Please describe.

Hello, I was wondering if we can return the Gotrue API response content to the client to provide a better experience for handling errors. 

As an example, while Signing Up an exception can be thrown with a 400 Status Code (Bad Request), this can occur if a user tries to sign up with the same email twice or something else and the exception object has only the HttpResponseMessage so the client cannot know what caused the exception only a 400 code without the GoTrue API message.

## Describe the solution you'd like

* Add Property Content to Exception objects that represent the message returned from GoTrue API.

Thank you very much.

**Comment by elrhomariyounes** [comment]
Hello @acupofjose, I submited a PR #2 could review it please.

Should we add this Content property or just access the message from the base property Exception.Message.

Thank you.

**Comment by acupofjose** [comment]
Great Idea. Merged!
