### ISSUE TITLE
SignIn method sends magic link

### ISSUE THREAD

**Issue by atnegrete** [supabase/gotrue-csharp#6]
First of all, great work, enjoying playing with this with .net core!

Why is the method name for sending a magic link called "SignIn" ? Kind of threw me off for a second.

Not sure if it's a bug or intentional. Thanks :)

**Comment by acupofjose** [comment]
@atnegrete at the time of writing it was mirroring the way the JS library did it - I’m happy to change it to something more intuitive. Say, `SendMagicLink`?

**Comment by atnegrete** [comment]
@acupofjose That sounds great! Thanks

**Comment by acupofjose** [comment]
Aliased in [v2.0.2](https://www.nuget.org/packages/gotrue-csharp/2.0.2) and [here in the code](https://github.com/supabase/gotrue-csharp/blob/master/Gotrue/Client.cs#L218).

Thanks for the suggestion @atnegrete!
